kidkeeper-rails/config/routes.rb
Rails.application.routes.draw do
  

  root 'pages#home'

  resources :telemetries
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

end

kidkeeper-rails/app/views/layouts/_header.html.erb
<nav class="navbar navbar-fluid navbar-inverse">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<!--allows for navbar-right links to collapse-->
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<!-- Logo redirects to dashboards instead of homepage when signed in -->
			<% if user_signed_in? %>
			<%= link_to 'KidKeeper', telemetry_path(current_user.telemetry), class: 'navbar-brand' %>
			<% else %> 
			<%= link_to 'KidKeeper', root_path, class: 'navbar-brand' %>
			<% end %>

		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<!-- non-collapse navbar order -->
			<ul class="nav navbar-nav navbar-right hidden-xs">
				<% if user_signed_in? %>
				<li><%= link_to current_user.email,  telemetry_path(current_user.telemetry) %></li>
				<li><%= link_to 'Sign Out', destroy_user_session_path, method: 'DELETE' %></li>
				<% else %>
				<li><%= link_to 'Sign Up', new_user_registration_path %></li>

				<li><%= link_to 'Sign In', new_user_session_path %></li>
				<% end %>
			</ul>

			<!-- collapsed navbar order -->
			<ul class="nav navbar-nav navbar-right visible-xs">
				<% if user_signed_in? %>
				<li><%= link_to current_user.email,  telemetry_path(current_user.telemetry) %></li>
				<li><%= link_to 'Sign Out', destroy_user_session_path %></li>
				<% else %>
				<li><%= link_to 'Sign In', new_user_session_path %></li>

				<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

kidkeeper-rails/app/views/layouts/_messages.html.erb
<% if devise_controller? %>
<%= devise_error_messages! %>
<% end %>

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
	<a href="#" data-dismiss="alert" class="close">×</a>
	<%= value %>
</div>
<% end %>

kidkeeper-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KidkeeperRails</title>

  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

</head>
<body>

<%= render 'layouts/header' %>

<%= render 'layouts/messages' %>

<%= yield %>

</body>
</html>