kidkeeper-rails/config/routes.rb
Rails.application.routes.draw do
  

  root 'pages#home'

  resources :telemetries
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

end

kidkeeper-rails/app/models/telemetry.rb
class Telemetry < ActiveRecord::Base
	belongs_to :user
end

kidkeeper-rails/app/controllers/telemetries_controller.rb
class TelemetriesController < ApplicationController

  before_action :authenticate_user!, except: [:update]

  before_action :find_telemetry, only: [:update, :destroy]

  # GET /telemetries
  # GET /telemetries.json
  def index
    @telemetries = Telemetry.all
  end

  # GET /telemetries/1
  # GET /telemetries/1.json
  def show
    @user = current_user 
    if @user.telemetry.nil?
      @telemetry = @user.build_telemetry
      @telemetry.save
    else
      @telemetry = @user.telemetry
    end

    gon.telemetryId = @telemetry.id
   end

  # GET /telemetries/new
  def new
    @telemetry = Telemetry.new
  end

  # GET /telemetries/1/edit
  def edit
  end

  # POST /telemetries
  # POST /telemetries.json
  def create
    @user = User.where(edison_token: params[:edison_token]).first
    @telemetry = @user.build_telemetry(telemetry_params)

    respond_to do |format|
      if @telemetry.save
        format.html { redirect_to @telemetry, notice: 'Telemetry was successfully created.' }
        format.json { render :show, status: :created, location: @telemetry }
      else
        format.html { render :new }
        format.json { render json: @telemetry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telemetries/1
  # PATCH/PUT /telemetries/1.json
  def update
      respond_to do |format|
        if @telemetry.update(telemetry_params)
          format.html { redirect_to @telemetry, notice: 'Telemetry was successfully updated.' }
          format.json { render :show, status: :ok, location: @telemetry }
        else
          format.html { render :edit }
          format.json { render json: @telemetry.errors, status: :unprocessable_entity }
        end
      end
    end

  # DELETE /telemetries/1
  # DELETE /telemetries/1.json
  def destroy
    @telemetry.destroy
    respond_to do |format|
      format.html { redirect_to telemetries_url, notice: 'Telemetry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_telemetry
    @user = User.where(edison_token: params[:edison_token]).first
    if @user.telemetry.nil?
      @telemetry = @user.build_telemetry
      @telemetry.save
    else
      @telemetry = @user.telemetry
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telemetry_params
      params.permit(:temp, :air_quality, :light, :sound, :humidity, :longitude, :latitude)
    end
  end

kidkeeper-rails/app/helpers/telemetries_helper.rb
module TelemetriesHelper
end

kidkeeper-rails/app/views/telemetries/_form.html.erb
<%= form_for(@telemetry) do |f| %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kidkeeper-rails/app/views/telemetries/edit.html.erb
<h1>Editing Telemetry</h1>

<%= render 'form' %>

<%= link_to 'Show', @telemetry %> |
<%= link_to 'Back', telemetries_path %>

kidkeeper-rails/app/views/telemetries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Telemetries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telemetries.each do |telemetry| %>
      <tr>
        <td><%= link_to 'Show', telemetry %></td>
        <td><%= link_to 'Edit', edit_telemetry_path(telemetry) %></td>
        <td><%= link_to 'Destroy', telemetry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telemetry', new_telemetry_path %>

kidkeeper-rails/app/views/telemetries/new.html.erb
<h1>New Telemetry</h1>

<%= render 'form' %>

<%= link_to 'Back', telemetries_path %>

kidkeeper-rails/app/views/telemetries/show.html.erb
<!DOCTYPE html>
<html>

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Kid Keeper</title>
    
    <link href='http://fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>

<style>
body {
    background-color: #151515;
    color: white;
}




body h3 {
    font-family: 'Roboto', sans-serif;
    margin-top: 50px;
    margin-left: 40px;

}

.header {
    background-color: black;
}
iframe {
    margin-left: 220px;
    margin-top: 0px;
    
}

.col-md-2 {
    
    border-style: solid;
    border-width: 1px;
    border-bottom-left-radius: 15px;
    border-bottom-right-radius: 15px;
    border-top-left-radius: 15px;
    border-top-right-radius: 15px;
    text-align: center;
    margin-top: 30px;
    margin-bottom: 20px;
    font-family: 'Roboto', sans-serif;
}

.col-md-2 h4 {
    font-size: 15px;
}



.col-md-2 h5 {
    padding-top: 30px;
    font-size: 30px;
}


footer p{
    display: inline;
    padding-right: 50px;
}
.jumbotron {
    position: relative;
    background: url("/assets/shutterstock_197442443.jpg") center center;
    width: 100%;
    height: 100%;
    background-size: cover;
    overflow: hidden;
}
</style>

    </head>
    
    
    <body>
        <div class="header">
        <h3>You are now tracking: John Smith</h3>
        </div>
        
        <div class="jumbotron">
    <div class="container">
             <div class="col-md-12">
       <iframe src="http://maps.google.com/maps?q=32.927923,77.627108&z=10&output=embed" width="700" height="300" frameborder="0" style="border:0" allowfullscreen id="google-maps"></iframe>
            
        </div>
        
        
        
        </div>
        
    
       
        
        <div class="col-md-1"></div>
        
        <div class="col-md-2">
        <h4>Air Quality</h4>
        <h2 id="air-quality">Loading...</h2>
        </div>
    
        
        <div class="col-md-2">
        <h4>Temperature</h4>
        <h2 id="temp">Loading...</h2>
        </div>
        
        <div class="col-md-2">
        <h4>Humidity</h4>
        <h2 id="humidity">Loading...</h2>
        </div>
        
        
        <div class="col-md-2">
        <h4>Sound</h4>
        <h2 id="sound">Loading...</h2>
        </div>
        
        <div class="col-md-2">
        <h4>Light</h4>
        <h2 id="light">Loading...</h2>

        </div>
    
    <div class="col-md-1"></div>
        
        
    <script src= "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jque ry.min.js"></script>
    <script src= "bootstrap/js/bootstrap.js"></script>
        
    </body>
        </div>

</html>
    